name: Code quality (Ruff)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install R
        run: |
          sudo apt-get update
          sudo apt-get install -y r-base r-base-dev
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Analyzing the code with Ruff
        run: |
          ruff check . --exit-zero
        continue-on-error: true
